swagger: "2.0"
info:
  title: Argent Bank Transaction API
  description: API for user transactions
  version: 2.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/account:
    post: 
      tags:
        - Accounts
      summary: All accounts
      description: API for fetching all user account
      security:
        - Bearer: []
      responses: 
        '200':
          description: All accounts fetch successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountResponse'
        '401':
          description: Unauthorized user
        '500':
          description: Internal Server Error
  /account/{accountId}/transactions:
    post:
      tags:
        - Accounts and Transactions
      summary: Account transactions
      description: API for retrieving list of transactions assiocated with an account
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: accountId
          description: Id of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{transactionId}/category:
    put:
      tags:
        - Accounts and Transactions
      summary: Update transaction's category
      description: API for updating category of transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of a transaction
          required: true
          type: string
        - in: body
          name: category
          description: Modified transaction's category
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      responses:
        '200':
          description: Transaction's category modified successfully
          schema: 
            $ref: '#/definitions/TransactionCategory'
        '401': 
          description: Unauthorized user
        '404': 
          description: Transaction not found
        '500': 
          description: Internal Servor Error
  /transactions/{transactionId}/note:
    post:
      tags:
        - Accounts and Transactions
      summary: Add transaction's note
      description: API for adding a note to a transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of a transaction
          required: true
          type: string
        - in: body
          name: note
          description: New transaction's note
          required: true
          schema: 
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note added to the transaction successfully
          schema: 
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Note not created
        '500':
          description: Internal Server Error
  /transactions/{transactionId}/note/{noteId}:
    put:
      tags:
        - Accounts and Transactions
      summary: Modify transaction's note
      description: API for modifying a note of a transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of a transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: Id of a note
          required: true
          type: string
        - in: body
          name: note
          description: Modify transaction's note
          required: true
          schema: 
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note modified successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Note not modified
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Accounts and Transactions Module
      summary: Delete transaction's note
      description: API for deleting a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of a transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: Id of a note
          required: true
          type: string
      responses:
        '200':
          description: Note deleted successfully
        '401':
          description: Unauthorized user
        '404':
          description: Note not deleted
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountResponse:
    type: object
    properties:
      accountName:
        type: string
        description: account name
      accountCurrency:
        type: string
        description: account currency
      currentBalance:
        type: number
        description: current account balance
        format: double
  TransactionResponse:
    type: object
    properties:
      date:
        type: string
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: string
        description: Amount of the transaction
      balance:
        type: string
        description: Balance after the transaction
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
  Detail:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string