swagger: "2.0"
info:
  title: Argent Bank Transaction API
  description: API for user transactions
  version: 2.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all user transactions
      description: API for retrieving list of transactions assiocated with an account
      security: 
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Id of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Account not found
        '500':
          description: Internal Server Error
  /user/transactions/{Id}:
    get:
      tags:
        - Transactions Module
      summary: Get transactions details depending on id
      description: API for retrieving all details of a transaction
      security: 
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Id of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema: 
            type: array
            items:
              $ref: '#/definitions/DetailsResponse'
        '401':
          description: Unauthorized user
        '404': 
          description: Account not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: Update transaction's category
      description: API for updating category of transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionId
          description: Id of a transaction
          required: true
          type: string
        - in: body
          name: category
          description: Modified transaction's category
          required: true
          schema:
            $ref: '#/definitions/EditTransactionDetails'
      responses:
        '200':
          description: Transaction's category modified successfully
          schema: 
            $ref: '#/definitions/DetailsResponse'
        '401': 
          description: Unauthorized user
        '404': 
          description: Transaction not found
        '500': 
          description: Internal Servor Error
    delete:
      tags:
        - Transactions Module
      summary: Delete transaction's note
      description: API for deleting a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: body
          name: deleteOptions
          description: Options for deletion
          required: true
          schema:
            type: object
            properties:
              deleteCategory:
                type: boolean
                description: Set to true if you want to delete the category
              deleteNote:
                type: boolean
                description: Set to true if you want to delete the note
      responses:
        '200':
          description: Note deleted successfully
        '401':
          description: Unauthorized user
        '404':
          description: Note not deleted
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsResponse:
     properties: 
        id:
          type: integer
          example: 2244
        date:
          type: string
          example: May 10th, 2024
        description:
            type: string
            example: Golden Sun Bakery
        amount:
            type: integer
            example: 8
        balance:
            type: integer
            example: 298.10
        type:
            type: string
            example: Electronic
  DetailsResponse:
     properties:
        Category:
          type: array
          example: 
            - Food 
            - Housing 
            - Deposit
            - Hobbies
            - Other
        selectedCategory: 
            type: string
            example: Food
        note:
            type: string
            example: Léa's birthday
  EditTransactionDetails:
    type: object
    properties:
      notes:
        type: string
        description: transaction additional notes
      category:
        type: string
        description: transaction category